services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: cartograph
      POSTGRES_PASSWORD: myDbPass123#
      POSTGRES_DB: cartograph
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cartograph-network
    ports:
      - "5444:5432"

  cartograph:
    build:
      context: .
      dockerfile: build/cartograph/docker/prod/Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: cartograph
      DB_PASS: myDbPass123#
      DB_PORT: 5432
      DB_USER: cartograph
    ports:
      - "8080:8080"
      - "8000:8000"
      - "443:443"
      - "80:80"
    volumes:
      - ./certificates:/ca-certificates
    networks:
      - cartograph-network

networks:
  cartograph-network:
    driver: bridge

volumes:
  postgres-data: